version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    hostname: kafka-server
    networks:
      - kafka-net    
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092
    depends_on:
      - zookeeper-server
  reactive-kafka-producer:
    image: vinodjagwani/reactive-kafka-producer
    networks:
      - kafka-net
    depends_on:
      - kafka-server
    ports:
      - 8081:8081
    environment:
      - KAFKA_HOST=kafka-server
      - KAFKA_PORT=29092
  reactive-kafka-consumer:
    image: vinodjagwani/reactive-kafka-consumer
    networks:
      - kafka-net
    depends_on:
      - kafka-server
    ports:
      - 8082:8082
    environment:
      - KAFKA_HOST=kafka-server
      - KAFKA_PORT=29092